Pipenv, requirements, pyproject
opengisch/qfieldcloud-sdk-python pull request #40
Opened 2023-07-13 16:06 UTC by why-not-try-calmer

Sorry I know how you dislike large PRs but these 3 things go hand in hand.

1. Making the life easier for dev encourages using a pinned version `requirements.txt` to start quickly.
2. When you have `requirements.txt` providing pinned versions, you want to have pyproject use requirement instead of declaring them manually.
3. But then when pyproject is complete, there is no longer any need for setup.py.
4. But when you do all this, you want to checks things, hence the extra checks in the CI.
5. Finally, with pyproject and requirements and pipenv working well, you want to restructre the package so that `src` is removed and the packaged bumped 1 level up; this also allows the developer to call the `main` of the package directly, so that the package will, when not imported and just run, automatically call the CLI.

2023-07-13 16:54 UTC, why-not-try-calmer commented on .gitignore
> +Pipfile*
let's have the user manage their Pipfile as they so please

2023-07-13 16:55 UTC, why-not-try-calmer commented on README.md
> +pipenv install -r requirements.txt
using `requirements.txt` helps if we want to let the user use pipenv or something else

2023-07-13 16:56 UTC, why-not-try-calmer commented on README.md
> +python -m qfieldcloud_sdk
Pro: Solves many problems at once:
- no need for entrypoint
- easier to package
- no need to manipulate the user's PATH envar
Con: requires changing the whole directory structure. Hence the number of files touched by this PR.

2023-07-13 16:57 UTC, why-not-try-calmer commented on qfieldcloud_sdk/__main__.py
> +if __name__ == "__main__":
to let users run the library as a package.

2023-07-13 16:58 UTC, why-not-try-calmer commented on pyproject.toml
> +
These changes to `pyproject.toml` are mandated by the fact that now we are using requirements.txt to pin dependencies.

2023-07-13 16:59 UTC, why-not-try-calmer commented on setup.py
> +        "click==8.1.5",
I'll add a commit to remove setup.py since it's a deprecated method. This means we will be able to use pyproject.toml only.

2023-07-13 20:01 UTC, why-not-try-calmer commented on .env.example
> -PYTHONPATH=${PWD}/src
Because of the new directory structure this should not be required.

2023-07-13 20:01 UTC, why-not-try-calmer commented on .github/workflows/continuous_integration.yml
> +      - name: Build tools
Ensuring this still is able to package.

2023-07-19 15:18 UTC, suricactus requested changes
```
[~]$ git clone https://github.com/opengisch/qfieldcloud-sdk-python /tmp/qfc-sdk-1 
Cloning into '/tmp/qfc-sdk-1'...
remote: Enumerating objects: 701, done.
remote: Counting objects: 100% (329/329), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 701 (delta 223), reused 220 (delta 206), pack-reused 372
Receiving objects: 100% (701/701), 111.32 KiB | 1.28 MiB/s, done.
Resolving deltas: 100% (299/299), done.
[~]$ cd /tmp/qfc-sdk-1 
[master][/tmp/qfc-sdk-1]$ git checkout easy-pipenv 
Branch 'easy-pipenv' set up to track remote branch 'easy-pipenv' from 'origin'.
Switched to a new branch 'easy-pipenv'
[easy-pipenv][/tmp/qfc-sdk-1]$ pipenv install -r requirements.txt
Creating a virtualenv for this project...
Pipfile: /tmp/qfc-sdk-1/Pipfile
Using /usr/bin/python3 (3.10.6) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.10.6.final.0-64 in 214ms
  creator CPython3Posix(dest=/home/suricactus/.local/share/virtualenvs/qfc-sdk-1-XWRakQqx, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/suricactus/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==68.0.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/suricactus/.local/share/virtualenvs/qfc-sdk-1-XWRakQqx
Creating a Pipfile for this project...
Requirements file provided! Importing into Pipfile...
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (d6cedb745ca78a38df99faad4ef4d0a8b2e645f7a6ccb730339374daad1e9e3e)!
Installing dependencies from Pipfile.lock (1e9e3e)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
[easy-pipenv][/tmp/qfc-sdk-1]$ pipenv install -r requirements.txt
Requirements file provided! Importing into Pipfile...
Installing dependencies from Pipfile.lock (1e9e3e)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
[easy-pipenv][/tmp/qfc-sdk-1]$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
[easy-pipenv][/tmp/qfc-sdk-1]$ pipenv shell
Launching subshell in virtual environment...
 . /home/suricactus/.local/share/virtualenvs/qfc-sdk-1-XWRakQqx/bin/activate
[easy-pipenv][/tmp/qfc-sdk-1]$  . /home/suricactus/.local/share/virtualenvs/qfc-sdk-1-XWRakQqx/bin/activate
(qfc-sdk-1) [easy-pipenv][/tmp/qfc-sdk-1]$ python -m qfieldcloud_sdk
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/qfc-sdk-1/qfieldcloud_sdk/__main__.py", line 1, in <module>
    from qfieldcloud_sdk import cli
  File "/tmp/qfc-sdk-1/qfieldcloud_sdk/cli.py", line 12, in <module>
    from qfieldcloud_sdk import sdk
  File "/tmp/qfc-sdk-1/qfieldcloud_sdk/sdk.py", line 21, in <module>
    __version__ = metadata.version("qfieldcloud_sdk")
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 984, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for qfieldcloud_sdk
```

Seems the instructions are still not working.

2023-07-19 15:36 UTC, why-not-try-calmer commented
> Seems the instructions are still not working.

The instructions are fine, insofar as they tell you how to install. To be sure, this PR is about making sure the project builds, packages and installs (see CI). What is preventing you from running the program is fixed in the other PR (see https://github.com/opengisch/qfieldcloud-sdk-python/pull/37/files#r1263023937).

2023-07-19 15:51 UTC, suricactus approved these changes
Ok, let's see.

2023-07-19 15:51 UTC, merged